### ISSUE TITLE
test timeouts on Windows

### ISSUE THREAD

**Issue by jeffmcaffer** [github/docs#230]
### What is the current behavior?
On windows I get dozens of test timeout failures some of which are shown below. These same tests pass fine on Mac. Running some of the tests individually from VS Code (using the Test Explorer extension) I do not get timeouts (for the ones I tried). 

Poking around a bit I see that on my reasonably powerful X1 Carbon with 16GB the tests peg the cpus at 100% and max out memory. I have a few other things running using about 8GB total. Looking at the processes there are 8 Node process running with several consuming considerably more than 1GB. I suspect that that is the bigger hit on perf than the CPU. 

Running the same tests on my recent-ish Macbook pro, the CPUs are not pegged (more like 50%) and memory use by the Node processes peaks at about 9.5GB. I've got a lot less going on on the Mac than the Windows machine so I suspect that and plain perf are what allow the tests to complete on Mac and not Windows.

Possible solutions:
* Length the timeout. Sorta unfortunate but folks with fast machines won't see an impact and folks with slower setups will be enabled
* throttle back Jest's concurrency either statically or with a user-setting. A quick look did not see a obvious setting. `maxConcurrency` appears to be for "intra-file" which are normally serial (unless you use test.concurrent` which we do not). This is less than optimal as that would impact folks with more powerful machines (if it was a static value).
* Slim down the test memory foot print. No idea what's taking 1.5GB to run on file of tests but perhaps there's something getting loaded or initialized that's not actually needed. That would speed up tests for everyone!
* other?

```
 FAIL  tests/routing/developer-site-redirects.js (167.618 s)
  ● developer redirects › redirects /v4 requests to /graphql › graphql homepage

    Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:29:45)

  ● developer redirects › redirects /v4 requests to /graphql › graphql enterprise homepage

    Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:29:45)
```

```
FAIL  tests/rendering/server.js (263.723 s)
  ● server › supports HEAD requests

    Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:29:45)

  ● server › renders the homepage

    Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:29:45)
```

@github/docs-engineering

**Comment by chiedo** [comment]
Connected with @jeffmcaffer. He's going to run point on this and I'm going to pair with him as needed to provide some additional engineering support!

**Comment by jeffmcaffer** [comment]
Did a bit more investigation and I don't think this is a "windows" problem per se. The tests are just running slowly. As observed ☝️ , they eat a lot of memory (saw a run peak at 10GB) and that contention will cause swap churn etc.  So, lower spec machines, machines that have a few chrome tabs open, ... will likely run into similar problems. 

As such, I'm going to update the title to be OS agnostic. I think the immediate term fix would be to up the timeout. Better would be to understand why the relevant tests are taking so long. In some cases there is just a lot going on but perhaps there are some perf opportunities.
